# Generated by Django 5.2.6 on 2025-09-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posting_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
    ]
